// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package lumas

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PluginService struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config               *_struct.Struct `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PluginService) Reset()         { *m = PluginService{} }
func (m *PluginService) String() string { return proto.CompactTextString(m) }
func (*PluginService) ProtoMessage()    {}
func (*PluginService) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *PluginService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginService.Unmarshal(m, b)
}
func (m *PluginService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginService.Marshal(b, m, deterministic)
}
func (m *PluginService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginService.Merge(m, src)
}
func (m *PluginService) XXX_Size() int {
	return xxx_messageInfo_PluginService.Size(m)
}
func (m *PluginService) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginService.DiscardUnknown(m)
}

var xxx_messageInfo_PluginService proto.InternalMessageInfo

func (m *PluginService) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PluginService) GetConfig() *_struct.Struct {
	if m != nil {
		return m.Config
	}
	return nil
}

type PluginRegistration struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PluginServices       []*PluginService `protobuf:"bytes,2,rep,name=pluginServices,proto3" json:"pluginServices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PluginRegistration) Reset()         { *m = PluginRegistration{} }
func (m *PluginRegistration) String() string { return proto.CompactTextString(m) }
func (*PluginRegistration) ProtoMessage()    {}
func (*PluginRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *PluginRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginRegistration.Unmarshal(m, b)
}
func (m *PluginRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginRegistration.Marshal(b, m, deterministic)
}
func (m *PluginRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginRegistration.Merge(m, src)
}
func (m *PluginRegistration) XXX_Size() int {
	return xxx_messageInfo_PluginRegistration.Size(m)
}
func (m *PluginRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_PluginRegistration proto.InternalMessageInfo

func (m *PluginRegistration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginRegistration) GetPluginServices() []*PluginService {
	if m != nil {
		return m.PluginServices
	}
	return nil
}

type RegisterResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	ErrorKind            string   `protobuf:"bytes,2,opt,name=errorKind,proto3" json:"errorKind,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResult) Reset()         { *m = RegisterResult{} }
func (m *RegisterResult) String() string { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()    {}
func (*RegisterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *RegisterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResult.Unmarshal(m, b)
}
func (m *RegisterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResult.Marshal(b, m, deterministic)
}
func (m *RegisterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResult.Merge(m, src)
}
func (m *RegisterResult) XXX_Size() int {
	return xxx_messageInfo_RegisterResult.Size(m)
}
func (m *RegisterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResult proto.InternalMessageInfo

func (m *RegisterResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *RegisterResult) GetErrorKind() string {
	if m != nil {
		return m.ErrorKind
	}
	return ""
}

func (m *RegisterResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PluginService)(nil), "lumas.PluginService")
	proto.RegisterType((*PluginRegistration)(nil), "lumas.PluginRegistration")
	proto.RegisterType((*RegisterResult)(nil), "lumas.RegisterResult")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x43, 0xab, 0x15, 0xa6, 0xda, 0xc3, 0x46, 0x23, 0x36, 0x8d, 0x21, 0x9c, 0x38, 0x2d,
	0x09, 0x5e, 0xfb, 0x03, 0x4c, 0xbc, 0x98, 0xad, 0x7f, 0x80, 0xe2, 0xb0, 0x6e, 0x02, 0x2c, 0xd9,
	0xd9, 0x35, 0xf1, 0xdf, 0x9b, 0x2e, 0x45, 0xa1, 0xb7, 0xe1, 0xcd, 0xe3, 0x7b, 0x6f, 0x16, 0x6e,
	0xfb, 0xc6, 0x49, 0xd5, 0xf1, 0xde, 0x68, 0xab, 0xd9, 0x75, 0xe3, 0xda, 0x92, 0xb6, 0x3b, 0xa9,
	0xb5, 0x6c, 0x30, 0xf7, 0xe2, 0xd1, 0xd5, 0x39, 0x59, 0xe3, 0x2a, 0x3b, 0x98, 0xd2, 0x0f, 0xb8,
	0x7b, 0xf7, 0x3f, 0x1d, 0xd0, 0x7c, 0xab, 0x0a, 0x19, 0x83, 0x2b, 0xfb, 0xd3, 0x63, 0x1c, 0x24,
	0x41, 0x16, 0x09, 0x3f, 0xb3, 0x1c, 0x56, 0x95, 0xee, 0x6a, 0x25, 0xe3, 0x45, 0x12, 0x64, 0xeb,
	0xe2, 0x91, 0x0f, 0x4c, 0x3e, 0x32, 0xf9, 0xc1, 0x33, 0xc5, 0xd9, 0x96, 0xd6, 0xc0, 0x06, 0xaa,
	0x40, 0xa9, 0xc8, 0x9a, 0xd2, 0x2a, 0xdd, 0x9d, 0xd0, 0x5d, 0xd9, 0xfe, 0xa1, 0x4f, 0x33, 0xdb,
	0xc3, 0xa6, 0x9f, 0xe6, 0x53, 0xbc, 0x48, 0x96, 0xd9, 0xba, 0xb8, 0xe7, 0xbe, 0x3d, 0x9f, 0x95,
	0x13, 0x17, 0xde, 0xf4, 0x0b, 0x36, 0x43, 0x02, 0x1a, 0x81, 0xe4, 0x1a, 0xcb, 0x9e, 0x01, 0xc8,
	0x55, 0x15, 0x12, 0xd5, 0xae, 0xf1, 0x49, 0xa1, 0x98, 0x28, 0x6c, 0x07, 0x11, 0x1a, 0xa3, 0xcd,
	0x9b, 0xea, 0x3e, 0xfd, 0x35, 0x91, 0xf8, 0x17, 0x58, 0x0c, 0x37, 0x2d, 0x12, 0x95, 0x12, 0xe3,
	0xa5, 0xdf, 0x8d, 0x9f, 0xc5, 0x2b, 0x84, 0x63, 0x12, 0xdb, 0x43, 0x68, 0xc6, 0xf9, 0x69, 0xd6,
	0x73, 0x7a, 0xee, 0xf6, 0xe1, 0xbc, 0x9a, 0x37, 0x3c, 0xae, 0xfc, 0xa3, 0xbd, 0xfc, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x74, 0xc4, 0x0b, 0xad, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterClient interface {
	Register(ctx context.Context, in *PluginRegistration, opts ...grpc.CallOption) (*RegisterResult, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) Register(ctx context.Context, in *PluginRegistration, opts ...grpc.CallOption) (*RegisterResult, error) {
	out := new(RegisterResult)
	err := c.cc.Invoke(ctx, "/lumas.Register/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServer is the server API for Register service.
type RegisterServer interface {
	Register(context.Context, *PluginRegistration) (*RegisterResult, error)
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumas.Register/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Register(ctx, req.(*PluginRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lumas.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register",
			Handler:    _Register_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
