// Code generated by protoc-gen-go. DO NOT EDIT.
// source: classification.proto

package processor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Image struct {
	Base64Image          string   `protobuf:"bytes,1,opt,name=base64Image,proto3" json:"base64Image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetBase64Image() string {
	if m != nil {
		return m.Base64Image
	}
	return ""
}

type FocusArea struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FocusArea) Reset()         { *m = FocusArea{} }
func (m *FocusArea) String() string { return proto.CompactTextString(m) }
func (*FocusArea) ProtoMessage()    {}
func (*FocusArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{1}
}

func (m *FocusArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FocusArea.Unmarshal(m, b)
}
func (m *FocusArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FocusArea.Marshal(b, m, deterministic)
}
func (m *FocusArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FocusArea.Merge(m, src)
}
func (m *FocusArea) XXX_Size() int {
	return xxx_messageInfo_FocusArea.Size(m)
}
func (m *FocusArea) XXX_DiscardUnknown() {
	xxx_messageInfo_FocusArea.DiscardUnknown(m)
}

var xxx_messageInfo_FocusArea proto.InternalMessageInfo

func (m *FocusArea) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *FocusArea) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *FocusArea) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *FocusArea) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type ImageToBeClassified struct {
	Image                *Image       `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	OutlineObjects       bool         `protobuf:"varint,2,opt,name=outlineObjects,proto3" json:"outlineObjects,omitempty"`
	ClassesToOutline     []string     `protobuf:"bytes,3,rep,name=classesToOutline,proto3" json:"classesToOutline,omitempty"`
	FocusAreas           []*FocusArea `protobuf:"bytes,4,rep,name=focusAreas,proto3" json:"focusAreas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ImageToBeClassified) Reset()         { *m = ImageToBeClassified{} }
func (m *ImageToBeClassified) String() string { return proto.CompactTextString(m) }
func (*ImageToBeClassified) ProtoMessage()    {}
func (*ImageToBeClassified) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{2}
}

func (m *ImageToBeClassified) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageToBeClassified.Unmarshal(m, b)
}
func (m *ImageToBeClassified) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageToBeClassified.Marshal(b, m, deterministic)
}
func (m *ImageToBeClassified) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageToBeClassified.Merge(m, src)
}
func (m *ImageToBeClassified) XXX_Size() int {
	return xxx_messageInfo_ImageToBeClassified.Size(m)
}
func (m *ImageToBeClassified) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageToBeClassified.DiscardUnknown(m)
}

var xxx_messageInfo_ImageToBeClassified proto.InternalMessageInfo

func (m *ImageToBeClassified) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ImageToBeClassified) GetOutlineObjects() bool {
	if m != nil {
		return m.OutlineObjects
	}
	return false
}

func (m *ImageToBeClassified) GetClassesToOutline() []string {
	if m != nil {
		return m.ClassesToOutline
	}
	return nil
}

func (m *ImageToBeClassified) GetFocusAreas() []*FocusArea {
	if m != nil {
		return m.FocusAreas
	}
	return nil
}

type Point struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{3}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Rectangle struct {
	BottomLeft           *Point   `protobuf:"bytes,1,opt,name=bottomLeft,proto3" json:"bottomLeft,omitempty"`
	TopRight             *Point   `protobuf:"bytes,2,opt,name=topRight,proto3" json:"topRight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rectangle) Reset()         { *m = Rectangle{} }
func (m *Rectangle) String() string { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()    {}
func (*Rectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{4}
}

func (m *Rectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rectangle.Unmarshal(m, b)
}
func (m *Rectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rectangle.Marshal(b, m, deterministic)
}
func (m *Rectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rectangle.Merge(m, src)
}
func (m *Rectangle) XXX_Size() int {
	return xxx_messageInfo_Rectangle.Size(m)
}
func (m *Rectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Rectangle.DiscardUnknown(m)
}

var xxx_messageInfo_Rectangle proto.InternalMessageInfo

func (m *Rectangle) GetBottomLeft() *Point {
	if m != nil {
		return m.BottomLeft
	}
	return nil
}

func (m *Rectangle) GetTopRight() *Point {
	if m != nil {
		return m.TopRight
	}
	return nil
}

type ImageSize struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageSize) Reset()         { *m = ImageSize{} }
func (m *ImageSize) String() string { return proto.CompactTextString(m) }
func (*ImageSize) ProtoMessage()    {}
func (*ImageSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{5}
}

func (m *ImageSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageSize.Unmarshal(m, b)
}
func (m *ImageSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageSize.Marshal(b, m, deterministic)
}
func (m *ImageSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageSize.Merge(m, src)
}
func (m *ImageSize) XXX_Size() int {
	return xxx_messageInfo_ImageSize.Size(m)
}
func (m *ImageSize) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageSize.DiscardUnknown(m)
}

var xxx_messageInfo_ImageSize proto.InternalMessageInfo

func (m *ImageSize) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ImageSize) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type ClassifiedObject struct {
	Boundary             *Rectangle `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Score                float32    `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	ImageSize            *ImageSize `protobuf:"bytes,3,opt,name=imageSize,proto3" json:"imageSize,omitempty"`
	ObjectClass          string     `protobuf:"bytes,4,opt,name=objectClass,proto3" json:"objectClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClassifiedObject) Reset()         { *m = ClassifiedObject{} }
func (m *ClassifiedObject) String() string { return proto.CompactTextString(m) }
func (*ClassifiedObject) ProtoMessage()    {}
func (*ClassifiedObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{6}
}

func (m *ClassifiedObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifiedObject.Unmarshal(m, b)
}
func (m *ClassifiedObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifiedObject.Marshal(b, m, deterministic)
}
func (m *ClassifiedObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifiedObject.Merge(m, src)
}
func (m *ClassifiedObject) XXX_Size() int {
	return xxx_messageInfo_ClassifiedObject.Size(m)
}
func (m *ClassifiedObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifiedObject.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifiedObject proto.InternalMessageInfo

func (m *ClassifiedObject) GetBoundary() *Rectangle {
	if m != nil {
		return m.Boundary
	}
	return nil
}

func (m *ClassifiedObject) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ClassifiedObject) GetImageSize() *ImageSize {
	if m != nil {
		return m.ImageSize
	}
	return nil
}

func (m *ClassifiedObject) GetObjectClass() string {
	if m != nil {
		return m.ObjectClass
	}
	return ""
}

type ClassifiedSounds struct {
	Score                      float32  `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	StartPresentationTimestamp int32    `protobuf:"varint,2,opt,name=startPresentationTimestamp,proto3" json:"startPresentationTimestamp,omitempty"`
	StopPresentationTimestamp  int32    `protobuf:"varint,3,opt,name=stopPresentationTimestamp,proto3" json:"stopPresentationTimestamp,omitempty"`
	Class                      string   `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *ClassifiedSounds) Reset()         { *m = ClassifiedSounds{} }
func (m *ClassifiedSounds) String() string { return proto.CompactTextString(m) }
func (*ClassifiedSounds) ProtoMessage()    {}
func (*ClassifiedSounds) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{7}
}

func (m *ClassifiedSounds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifiedSounds.Unmarshal(m, b)
}
func (m *ClassifiedSounds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifiedSounds.Marshal(b, m, deterministic)
}
func (m *ClassifiedSounds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifiedSounds.Merge(m, src)
}
func (m *ClassifiedSounds) XXX_Size() int {
	return xxx_messageInfo_ClassifiedSounds.Size(m)
}
func (m *ClassifiedSounds) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifiedSounds.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifiedSounds proto.InternalMessageInfo

func (m *ClassifiedSounds) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ClassifiedSounds) GetStartPresentationTimestamp() int32 {
	if m != nil {
		return m.StartPresentationTimestamp
	}
	return 0
}

func (m *ClassifiedSounds) GetStopPresentationTimestamp() int32 {
	if m != nil {
		return m.StopPresentationTimestamp
	}
	return 0
}

func (m *ClassifiedSounds) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

type Classification struct {
	Sounds               []*ClassifiedSounds `protobuf:"bytes,1,rep,name=sounds,proto3" json:"sounds,omitempty"`
	Objects              []*ClassifiedObject `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Classification) Reset()         { *m = Classification{} }
func (m *Classification) String() string { return proto.CompactTextString(m) }
func (*Classification) ProtoMessage()    {}
func (*Classification) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{8}
}

func (m *Classification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Classification.Unmarshal(m, b)
}
func (m *Classification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Classification.Marshal(b, m, deterministic)
}
func (m *Classification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Classification.Merge(m, src)
}
func (m *Classification) XXX_Size() int {
	return xxx_messageInfo_Classification.Size(m)
}
func (m *Classification) XXX_DiscardUnknown() {
	xxx_messageInfo_Classification.DiscardUnknown(m)
}

var xxx_messageInfo_Classification proto.InternalMessageInfo

func (m *Classification) GetSounds() []*ClassifiedSounds {
	if m != nil {
		return m.Sounds
	}
	return nil
}

func (m *Classification) GetObjects() []*ClassifiedObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

type AudioToBeClassified struct {
	Audio                []byte   `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Codec                string   `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioToBeClassified) Reset()         { *m = AudioToBeClassified{} }
func (m *AudioToBeClassified) String() string { return proto.CompactTextString(m) }
func (*AudioToBeClassified) ProtoMessage()    {}
func (*AudioToBeClassified) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f68caa38e675f74, []int{9}
}

func (m *AudioToBeClassified) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioToBeClassified.Unmarshal(m, b)
}
func (m *AudioToBeClassified) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioToBeClassified.Marshal(b, m, deterministic)
}
func (m *AudioToBeClassified) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioToBeClassified.Merge(m, src)
}
func (m *AudioToBeClassified) XXX_Size() int {
	return xxx_messageInfo_AudioToBeClassified.Size(m)
}
func (m *AudioToBeClassified) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioToBeClassified.DiscardUnknown(m)
}

var xxx_messageInfo_AudioToBeClassified proto.InternalMessageInfo

func (m *AudioToBeClassified) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *AudioToBeClassified) GetCodec() string {
	if m != nil {
		return m.Codec
	}
	return ""
}

func init() {
	proto.RegisterType((*Image)(nil), "processor.Image")
	proto.RegisterType((*FocusArea)(nil), "processor.FocusArea")
	proto.RegisterType((*ImageToBeClassified)(nil), "processor.ImageToBeClassified")
	proto.RegisterType((*Point)(nil), "processor.Point")
	proto.RegisterType((*Rectangle)(nil), "processor.Rectangle")
	proto.RegisterType((*ImageSize)(nil), "processor.ImageSize")
	proto.RegisterType((*ClassifiedObject)(nil), "processor.ClassifiedObject")
	proto.RegisterType((*ClassifiedSounds)(nil), "processor.ClassifiedSounds")
	proto.RegisterType((*Classification)(nil), "processor.Classification")
	proto.RegisterType((*AudioToBeClassified)(nil), "processor.AudioToBeClassified")
}

func init() { proto.RegisterFile("classification.proto", fileDescriptor_6f68caa38e675f74) }

var fileDescriptor_6f68caa38e675f74 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x51, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0xbd, 0xa6, 0x17, 0x73, 0x93, 0x52, 0xc2, 0x36, 0xc8, 0xb5, 0x82, 0x84, 0x15, 0x6a,
	0x14, 0x09, 0x25, 0xad, 0x3e, 0x89, 0x10, 0x0b, 0x8a, 0x20, 0xb4, 0x6c, 0xe3, 0xab, 0xb0, 0xb9,
	0x6c, 0x92, 0xd5, 0xe4, 0x26, 0xdc, 0x6e, 0xb0, 0x11, 0x3f, 0x94, 0x1f, 0xc0, 0x77, 0xbf, 0x96,
	0xdc, 0xec, 0xe5, 0x72, 0x39, 0x93, 0xe0, 0xe3, 0xcc, 0xfd, 0x6f, 0xee, 0xf7, 0xff, 0xef, 0xec,
	0x41, 0x33, 0x9a, 0x4a, 0x63, 0xf4, 0x48, 0x47, 0xd2, 0x6a, 0x8c, 0x3b, 0xf3, 0x04, 0x2d, 0xb2,
	0x60, 0x9e, 0x60, 0xa4, 0x8c, 0xc1, 0x84, 0x3f, 0x07, 0xff, 0xe3, 0x4c, 0x8e, 0x15, 0x6b, 0x41,
	0x7d, 0x20, 0x8d, 0x7a, 0x7d, 0x45, 0x65, 0xe8, 0xb5, 0xbc, 0x76, 0x20, 0x8a, 0x2d, 0xfe, 0x19,
	0x82, 0xf7, 0x18, 0x2d, 0x4c, 0x2f, 0x51, 0x92, 0x1d, 0x81, 0x77, 0x4f, 0x22, 0x5f, 0x78, 0xf7,
	0x69, 0xb5, 0x0c, 0x0f, 0x5c, 0xb5, 0x64, 0x8f, 0xa0, 0x3a, 0x51, 0x7a, 0x3c, 0xb1, 0x61, 0x85,
	0x5a, 0x59, 0xc5, 0x9a, 0xe0, 0x7f, 0xd7, 0x43, 0x3b, 0x09, 0x0f, 0xa9, 0xed, 0x0a, 0xfe, 0xc7,
	0x83, 0x13, 0xfa, 0x40, 0x1f, 0xdf, 0xa9, 0xeb, 0x0c, 0x57, 0x0d, 0xd9, 0x39, 0xf8, 0x3a, 0x47,
	0xa9, 0x77, 0x1b, 0x9d, 0x1c, 0xba, 0x43, 0x72, 0xe1, 0x1e, 0xb3, 0x73, 0x38, 0xc6, 0x85, 0x9d,
	0xea, 0x58, 0xdd, 0x0c, 0xbe, 0xaa, 0xc8, 0x1a, 0x02, 0xa9, 0x89, 0x52, 0x97, 0xbd, 0x80, 0x06,
	0x85, 0xa1, 0x4c, 0x1f, 0x6f, 0xdc, 0xa3, 0xb0, 0xd2, 0xaa, 0xb4, 0x03, 0xf1, 0x4f, 0x9f, 0x5d,
	0x01, 0x8c, 0x56, 0x56, 0x4d, 0x78, 0xd8, 0xaa, 0xb4, 0xeb, 0xdd, 0x66, 0x01, 0x20, 0xcf, 0x41,
	0x14, 0x74, 0xfc, 0x29, 0xf8, 0xb7, 0xa8, 0x63, 0xbb, 0x2f, 0x1c, 0xfe, 0x0d, 0x02, 0xa1, 0x22,
	0x2b, 0xe3, 0xf1, 0x54, 0xb1, 0x0b, 0x80, 0x01, 0x5a, 0x8b, 0xb3, 0x4f, 0x6a, 0x64, 0xb7, 0x18,
	0xa5, 0x71, 0xa2, 0xa0, 0x61, 0x2f, 0xa1, 0x66, 0x71, 0x2e, 0x28, 0xdd, 0x83, 0x1d, 0xfa, 0x5c,
	0xc1, 0x9f, 0x41, 0x40, 0x59, 0xdd, 0xe9, 0x1f, 0x6a, 0x2f, 0xd5, 0x2f, 0x0f, 0x1a, 0xeb, 0xec,
	0x5d, 0x64, 0xec, 0x02, 0x6a, 0x03, 0x5c, 0xc4, 0x43, 0x99, 0x2c, 0x33, 0xb6, 0x62, 0x06, 0xb9,
	0x0b, 0x91, 0xab, 0xd2, 0x13, 0x36, 0x11, 0x26, 0x8a, 0x06, 0x1f, 0x08, 0x57, 0xb0, 0x2e, 0x04,
	0x7a, 0x45, 0x41, 0x2b, 0xb1, 0x39, 0x28, 0x27, 0x14, 0x6b, 0x59, 0xba, 0x8e, 0x48, 0x14, 0x44,
	0x45, 0x1b, 0x13, 0x88, 0x62, 0x8b, 0xff, 0xde, 0x40, 0xbe, 0x4b, 0x11, 0xcc, 0x1a, 0xc0, 0x2b,
	0x02, 0xbc, 0x85, 0x33, 0x63, 0x65, 0x62, 0x6f, 0x13, 0x65, 0x54, 0x6c, 0xe9, 0x2a, 0xf4, 0xf5,
	0x4c, 0x19, 0x2b, 0x67, 0xf3, 0x2c, 0x84, 0x3d, 0x0a, 0xf6, 0x06, 0x4e, 0x8d, 0xc5, 0xf9, 0xf6,
	0xd7, 0xdd, 0x8e, 0xef, 0x16, 0xa4, 0x4c, 0x51, 0xc1, 0x84, 0x2b, 0xf8, 0x4f, 0x38, 0xbe, 0xde,
	0xb8, 0x9b, 0xec, 0x12, 0xaa, 0x86, 0x5c, 0x84, 0x1e, 0x2d, 0xdc, 0xe3, 0x42, 0x46, 0x65, 0xa3,
	0x22, 0x93, 0xb2, 0x57, 0xf0, 0x10, 0xf3, 0xb5, 0xdf, 0xfd, 0x96, 0x3b, 0x51, 0xb1, 0xd2, 0xf2,
	0x1e, 0x9c, 0xf4, 0x16, 0x43, 0x8d, 0xa5, 0x3b, 0xd7, 0x04, 0x5f, 0xa6, 0x6d, 0x8a, 0xef, 0x48,
	0xb8, 0x82, 0x0c, 0xe0, 0x50, 0x45, 0x94, 0x54, 0x6a, 0x20, 0x2d, 0xba, 0x5f, 0xb2, 0x6b, 0x5b,
	0x72, 0xf1, 0x01, 0x6a, 0xd9, 0x3f, 0x67, 0xc9, 0x9e, 0x94, 0x4f, 0x79, 0xf3, 0x73, 0x67, 0xa7,
	0x5b, 0x58, 0xdd, 0x18, 0xfe, 0x20, 0x9d, 0x4f, 0x88, 0xff, 0x39, 0x7f, 0x8b, 0x9d, 0xbd, 0xf3,
	0x07, 0x55, 0xfa, 0x17, 0x5e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xa8, 0x6e, 0xe7, 0x23,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImageClassificationClient is the client API for ImageClassification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageClassificationClient interface {
	Classify(ctx context.Context, in *ImageToBeClassified, opts ...grpc.CallOption) (*Classification, error)
}

type imageClassificationClient struct {
	cc *grpc.ClientConn
}

func NewImageClassificationClient(cc *grpc.ClientConn) ImageClassificationClient {
	return &imageClassificationClient{cc}
}

func (c *imageClassificationClient) Classify(ctx context.Context, in *ImageToBeClassified, opts ...grpc.CallOption) (*Classification, error) {
	out := new(Classification)
	err := c.cc.Invoke(ctx, "/processor.ImageClassification/classify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageClassificationServer is the server API for ImageClassification service.
type ImageClassificationServer interface {
	Classify(context.Context, *ImageToBeClassified) (*Classification, error)
}

// UnimplementedImageClassificationServer can be embedded to have forward compatible implementations.
type UnimplementedImageClassificationServer struct {
}

func (*UnimplementedImageClassificationServer) Classify(ctx context.Context, req *ImageToBeClassified) (*Classification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}

func RegisterImageClassificationServer(s *grpc.Server, srv ImageClassificationServer) {
	s.RegisterService(&_ImageClassification_serviceDesc, srv)
}

func _ImageClassification_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageToBeClassified)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageClassificationServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processor.ImageClassification/Classify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageClassificationServer).Classify(ctx, req.(*ImageToBeClassified))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageClassification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "processor.ImageClassification",
	HandlerType: (*ImageClassificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "classify",
			Handler:    _ImageClassification_Classify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classification.proto",
}

// AudioClassificationClient is the client API for AudioClassification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AudioClassificationClient interface {
	Classify(ctx context.Context, in *AudioToBeClassified, opts ...grpc.CallOption) (*Classification, error)
}

type audioClassificationClient struct {
	cc *grpc.ClientConn
}

func NewAudioClassificationClient(cc *grpc.ClientConn) AudioClassificationClient {
	return &audioClassificationClient{cc}
}

func (c *audioClassificationClient) Classify(ctx context.Context, in *AudioToBeClassified, opts ...grpc.CallOption) (*Classification, error) {
	out := new(Classification)
	err := c.cc.Invoke(ctx, "/processor.AudioClassification/classify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioClassificationServer is the server API for AudioClassification service.
type AudioClassificationServer interface {
	Classify(context.Context, *AudioToBeClassified) (*Classification, error)
}

// UnimplementedAudioClassificationServer can be embedded to have forward compatible implementations.
type UnimplementedAudioClassificationServer struct {
}

func (*UnimplementedAudioClassificationServer) Classify(ctx context.Context, req *AudioToBeClassified) (*Classification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}

func RegisterAudioClassificationServer(s *grpc.Server, srv AudioClassificationServer) {
	s.RegisterService(&_AudioClassification_serviceDesc, srv)
}

func _AudioClassification_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioToBeClassified)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioClassificationServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processor.AudioClassification/Classify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioClassificationServer).Classify(ctx, req.(*AudioToBeClassified))
	}
	return interceptor(ctx, in, info, handler)
}

var _AudioClassification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "processor.AudioClassification",
	HandlerType: (*AudioClassificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "classify",
			Handler:    _AudioClassification_Classify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classification.proto",
}
